/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scooter.glb --k -K s -T -R 2048 -j -f 
Files: scooter.glb [14.13MB] > /Users/macbookprom1/Documents/izzy-r3f/public/scooter-transformed.glb [1.04MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scooter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube019" position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.main} />
          <points name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.main} />
        </group>
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials.emission} position={[0.073, 0.131, -2.183]} rotation={[0, 0, -0.25]} />
        <group name="Cube013" position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]}>
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.emission} />
          <points name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials.emission} />
        </group>
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.emission} position={[0.199, 1.064, -2.184]} rotation={[0, 0, -0.245]} scale={[0.104, 0.104, 0.078]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scooter-transformed.glb')
